version: 2.1
jobs:
  build-test:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
          name: Build Containers
          command: docker-compose build
      - run:
          name: Start Containers
          command: docker-compose up -d
      - run:
          name: sleep for waiting launch db
          command: sleep 10
      - run:
          name: Run Test
          command: |
            docker-compose run django-service pytest -v
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1
      - run:
          name: docker-compose down
          command: docker-compose down

  build_images-push:
    docker:
      - image: docker:18.09.0
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: install aws cli
          command: |
            apk add --no-cache --update py-pip
            pip install awscli
      - run:
          name: build image
          command: |
            $(aws ecr get-login --no-include-email --region ${AWS_DEFAULT_REGION})
            docker build -t ${ECR_DOMAIN}/django:$CIRCLE_SHA1 -t ${ECR_DOMAIN}/django:latest ./django_service
            docker build -t ${ECR_DOMAIN}/nginx:$CIRCLE_SHA1 -t ${ECR_DOMAIN}/nginx:latest ./nginx
      - run:
          name: Push Docker Image
          command: |
            docker push ${ECR_DOMAIN}/django:$CIRCLE_SHA1
            docker push ${ECR_DOMAIN}/django:latest
            docker push ${ECR_DOMAIN}/nginx:$CIRCLE_SHA1
            docker push ${ECR_DOMAIN}/nginx:latest

  deploy-test:
    docker:
      - image: circleci/python:3.7
    steps:
      - run:
          name: install aws cli
          command: |
            sudo pip install awscli
      - run:
          name: download jq
          command: |
            wget https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
            mv jq-linux64 jq
      - run:
          name: Setup common environment variables
          command: |
            echo 'export ECS_CLUSTER_NAME="${AWS_RESOURCE_NAME_PREFIX}-cluster"' >> $BASH_ENV
            echo 'export ECS_SERVICE_NAME="${AWS_RESOURCE_NAME_PREFIX}-service"' >> $BASH_ENV
            echo 'export TASK_DEFINITION_NAME="${AWS_RESOURCE_NAME_PREFIX}-service"' >> $BASH_ENV
            echo 'export FULL_IMAGE_NAME="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${AWS_RESOURCE_NAME_PREFIX}:${CIRCLE_SHA1}"' >> $BASH_ENV
      - run:
          name: aws ecr login
          command: |
            $(aws ecr get-login --no-include-email --region ${AWS_DEFAULT_REGION})
      - run:
          name: aws ecs deploy
          command: |
            aws ecs describe-task-definition --task-definition $TASK_DEFINITION_NAME | 
            jq '.taskDefinition | { containerDefinitions: .containerDefinitions, volumes: .volumes }' > definition.json
            aws ecs register-task-definition --family $ECS_SERVICE_NAME --cli-input-json file://definition.json
            aws ecs update-service --cluster $ECS_CLUSTER_NAME --service $ECS_SERVICE_NAME --task-definition $TASK_DEFINITION_NAME
      - run:
          name: ecs migration
          command: |
            aws ecs run-task --cluster django-cluster --task-definition django-migrate
      - run:
          name: Test deployment
          command: |
            TARGET_GROUP_ARN=$(aws ecs describe-services --cluster $ECS_CLUSTER_NAME --services $ECS_SERVICE_NAME | jq -r '.services[0].loadBalancers[0].targetGroupArn')
            ELB_ARN=$(aws elbv2 describe-target-groups --target-group-arns $TARGET_GROUP_ARN | jq -r '.TargetGroups[0].LoadBalancerArns[0]')
            ELB_DNS_NAME=$(aws elbv2 describe-load-balancers --load-balancer-arns $ELB_ARN | jq -r '.LoadBalancers[0].DNSName')
            # Test multiple times to verify that the new revision has been deployed across the entire cluster
            for attempt in {1..10}; do
              curl -s --retry 10 https://worklog-management.ml
            done

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build-test
      - build_images-push:
          requires:
            - build-test
      - deploy-test:
          requires:
            - build_images-push