# Generated by Django 2.1.8 on 2019-05-04 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sample', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
