# Generated by Django 2.1.8 on 2019-05-04 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sample', '0002_test_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
