# Generated by Django 2.1.8 on 2019-05-04 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sample', '0003_delete_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
